[package]
name = "rfc4251"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0"

[dev-dependencies]
serde = { version = "1.0", features=["derive"] }
